import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# Font Registration for Indic Unicode Support
FONTS_SEARCH_PATHS = [
    (r"C:\Windows\Fonts\mangal.ttf", "Mangal"),
    (r"C:\Windows\Fonts\aparaj.ttf", "Aparajita"),
    (r"C:\Windows\Fonts\nirmala.ttf", "Nirmala"),
]

UNICODE_FONT = None
for font_path, font_name in FONTS_SEARCH_PATHS:
    if os.path.exists(font_path):
        try:
            pdfmetrics.registerFont(TTFont(font_name, font_path))
            UNICODE_FONT = font_name
            break
        except Exception:
            pass

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to compute total pages and render top/bottom page decorations."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        # Top Header Accent Line
        self.setStrokeColor(colors.HexColor("#15803d"))
        self.setLineWidth(1)
        self.line(36, 806, 559, 806)
        
        # Footer
        font_name = UNICODE_FONT or "Helvetica"
        self.setFont(font_name, 8)
        self.setFillColor(colors.HexColor("#64748b"))
        self.drawString(36, 25, "AgroVision AI — Official Verified Farmer Credentials Report")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(559, 25, page_str)
        
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 36, 559, 36)
        self.restoreState()
def xml_escape(text):
    if not text:
        return ""
    s = str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return s

class ReportGenerator:
    def __init__(self):
        self.reports_dir = os.path.join(os.path.dirname(__file__), "reports")
        if not os.path.exists(self.reports_dir):
            os.makedirs(self.reports_dir)
            
        # Multilingual Labels & Translations for PDF Output
        self.i18n = {
            "English": {
                "title": "AgroVision: AI Farmer Official Report",
                "gen_date": "Generated on",
                "profile_sec": "Farmer Profile & Farm Credentials",
                "name": "Farmer Name",
                "location": "State Location",
                "land_size": "Land Holding Area",
                "land_type": "Soil / Land Type",
                "irrigation": "Irrigation Facility",
                "crops": "Cultivated Crops",
                "schemes_sec": "Eligible Government Subsidies & Schemes",
                "scheme_col_name": "Scheme Name & Match",
                "scheme_col_benefits": "Benefits & Scope",
                "scheme_col_docs": "Required Documents",
                "benefits": "Benefits",
                "required_docs": "Required Documents",
                "crop_advice_sec": "AI Crop Advisor Recommendation",
                "rec_crop": "Recommended Crop",
                "ai_insight": "AI Agronomist Advice",
                "summary_sec": "Summary & Next Steps",
                "summary_text": "This report is generated by AgroVision AI. Based on your profile, you are eligible for several government subsidies and crop schemes that significantly increase your farm ROI. Apply at your nearest Agriculture Office or Online portal.",
                "match_label": "Match",
                "default_crop": "Suggested based on profile",
                "default_reason": "Matching schemes found for your specific land and crop types."
            },
            "हिंदी": {
                "title": "एग्रोविज़न: एआई किसान आधिकारिक रिपोर्ट",
                "gen_date": "जारी करने की तारीख",
                "profile_sec": "किसान प्रोफाइल विवरण",
                "name": "किसान का नाम",
                "location": "राज्य / स्थान",
                "land_size": "भूमि का आकार",
                "land_type": "मिट्टी का प्रकार",
                "irrigation": "सिंचाई की स्थिति",
                "crops": "प्रमुख फसलें",
                "schemes_sec": "पात्र सरकारी योजनाएं और सब्सिडी",
                "scheme_col_name": "योजना का नाम और मिलान",
                "scheme_col_benefits": "लाभ और विवरण",
                "scheme_col_docs": "आवश्यक दस्तावेज",
                "benefits": "लाभ",
                "required_docs": "आवश्यक दस्तावेज",
                "crop_advice_sec": "एआई फसल सलाह और सिफारिश",
                "rec_crop": "अनुशंसित फसल",
                "ai_insight": "कृषि विशेषज्ञ सलाह",
                "summary_sec": "पूर्वानुमान सारांश",
                "summary_text": "यह रिपोर्ट एग्रोविज़न एआई द्वारा तैयार की गई है। आपकी प्रोफ़ाइल के अनुसार, आप कई सरकारी सब्सिडी और योजनाओं के पात्र हैं। निकटतम कृषि कार्यालय या ऑनलाइन पोर्टल पर आवेदन करें।",
                "match_label": "मेल",
                "default_crop": "प्रोफ़ाइल के आधार पर अनुशंसित",
                "default_reason": "आपकी भूमि और फसल के अनुसार उपयुक्त योजनाएं पाई गईं।"
            },
            "मराठी": {
                "title": "ॲग्रोव्हिजन: एआय शेतकरी अधिकृत अहवाल",
                "gen_date": "अहवाल तारीख",
                "profile_sec": "शेतकरी प्रोफाइल व शेत माहिती",
                "name": "शेतकऱ्याचे नाव",
                "location": "राज्य / जिल्हा",
                "land_size": "जमिनीचे क्षेत्र",
                "land_type": "मातीचा प्रकार",
                "irrigation": "पाण्याची उपलब्धता",
                "crops": "मुख्य पिके",
                "schemes_sec": "पात्र सरकारी योजना व अनुदाने",
                "scheme_col_name": "योजनेचे नाव व जुळणी",
                "scheme_col_benefits": "फायदे व स्वरूप",
                "scheme_col_docs": "आवश्यक कागदपत्रे",
                "benefits": "फायदे",
                "required_docs": "आवश्यक कागदपत्रे",
                "crop_advice_sec": "एआय पीक सल्ला व शिफारस",
                "rec_crop": "शिफारस केलेले पीक",
                "ai_insight": "कृषी तज्ज्ञ सल्ला",
                "summary_sec": "अहवाल सारांश",
                "summary_text": "हा अहवाल ॲग्रोव्हिजन एआई प्रणालीद्वारे तयार केला आहे. आपल्या शेतीच्या माहितीनुसार, आपण विविध सरकारी योजना व अनुदानांसाठी पात्र आहात. त्वरित अर्ज करून योजनेचा लाभ घ्या.",
                "match_label": "जुळणी",
                "default_crop": "प्रोफाईलवर आधारित पीक",
                "default_reason": "तुमच्या शेतीच्या घटकांनुसार पात्र योजना व शिफारसी उपलब्ध आहेत."
            },
            "తెలుగు": {
                "title": "అగ్రోవిజన్: AI రైతు అధికారిక నివేదిక",
                "gen_date": "తయారు చేసిన తేదీ",
                "profile_sec": "రైతు ప్రొఫైల్ వివరాలు",
                "name": "రైతు పేరు",
                "location": "రాష్ట్రం / ప్రాంతం",
                "land_size": "భూమి విస్తీర్ణం",
                "land_type": "నేల రకం",
                "irrigation": "నీటి సౌకర్యం",
                "crops": "పండించే పంటలు",
                "schemes_sec": "అర్హత కలిగిన ప్రభుత్వ పథకాలు & రాయితీలు",
                "scheme_col_name": "పథకం పేరు & మ్యాచింగ్",
                "scheme_col_benefits": "ప్రయోజనాలు & వివరాలు",
                "scheme_col_docs": "కావలసిన పత్రాలు",
                "benefits": "ప్రయోజనాలు",
                "required_docs": "కావలసిన పత్రాలు",
                "crop_advice_sec": "AI పంట సలహా & సిఫార్సు",
                "rec_crop": "సిఫార్సు చేసిన పంట",
                "ai_insight": "వ్యవసాయ నిపుణుల సలహా",
                "summary_sec": "ముగింపు సారాంశం",
                "summary_text": "ఈ నివేదిక అగ్రోవిజన్ AI ద్వారా రూపొందించబడింది. మీ ప్రొఫైల్ ఆధారంగా, మీరు అనేక ప్రభుత్వ పథకాలు మరియు రాయితీలకు అర్హులు.",
                "match_label": "మ్యాచింగ్",
                "default_crop": "ప్రొఫైల్ ఆధారంగా సిఫార్సు చేయబడింది",
                "default_reason": "మీ భూమి మరియు పంట ఆధారంగా అనుకూలమైన పథకాలు కనుగొనబడ్డాయి."
            },
            "മലയാളം": {
                "title": "ആഗ്രോ വിഷൻ: AI കർഷക ഔദ്യോഗിക റിപ്പോർട്ട്",
                "gen_date": "തയ്യാറാക്കിയ തീയതി",
                "profile_sec": "കർഷക പ്രൊഫൈൽ വിവരങ്ങൾ",
                "name": "കർഷകന്റെ പേര്",
                "location": "സംസ്ഥാനം / സ്ഥലം",
                "land_size": "ഭൂമിയുടെ അളവ്",
                "land_type": "മണ്ണിന്റെ തരം",
                "irrigation": "ജലസേചന സൗകര്യം",
                "crops": "കൃഷി ചെയ്യുന്ന വിളകൾ",
                "schemes_sec": "യോഗ്യതയുള്ള സർക്കാർ പദ്ധതികൾ",
                "scheme_col_name": "പദ്ധതിയുടെ പേര്",
                "scheme_col_benefits": "ആനുകൂല്യങ്ങൾ",
                "scheme_col_docs": "ആവശ്യമായ രേഖകൾ",
                "benefits": "ആനുകൂല്യങ്ങൾ",
                "required_docs": "ആവശ്യമായ രേഖകൾ",
                "crop_advice_sec": "AI വിള ഉപദേശവും നിർദ്ദേശവും",
                "rec_crop": "നിർദ്ദേശിച്ച വിള",
                "ai_insight": "കാർഷിക വിദഗ്ദ്ധ ഉപദേശം",
                "summary_sec": "റിപ്പോർട്ട് സംഗ്രഹം",
                "summary_text": "ഈ റിപ്പോർട്ട് ആഗ്രോവിഷൻ AI തയ്യാറാക്കിയതാണ്. നിങ്ങളുടെ പ്രൊഫൈൽ അനുസരിച്ച് നിങ്ങൾക്ക് നിരവധി സർക്കാർ പദ്ധതികൾക്ക് യോഗ്യതയുണ്ട്.",
                "match_label": "മാച്ച്",
                "default_crop": "പ്രൊഫൈൽ അടിസ്ഥാനമാക്കി നിർദ്ദേശിച്ചത്",
                "default_reason": "നിങ്ങളുടെ പ്രൊഫൈലിന് അനുയോജ്യമായ പദ്ധതികൾ കണ്ടെത്തി."
            },
            "ਪੰਜਾਬੀ": {
                "title": "ਐਗਰੋਵਿਜ਼ਨ: AI ਕਿਸਾਨ ਅਧਿਕਾਰਤ ਰਿਪੋਰਟ",
                "gen_date": "ਰਿਪੋਰਟ ਦੀ ਮਿਤੀ",
                "profile_sec": "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਵੇਰਵੇ",
                "name": "ਕਿਸਾਨ ਦਾ ਨਾਮ",
                "location": "ਰਾਜ / ਜ਼ਿਲ੍ਹਾ",
                "land_size": "ਜ਼ਮੀਨ ਦਾ ਖੇਤਰਫਲ",
                "land_type": "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
                "irrigation": "ਸਿੰਚਾਈ ਦੀ ਸਹੂਲਤ",
                "crops": "ਮੁੱਖ ਫਸਲਾਂ",
                "schemes_sec": "ਯੋਗ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਸਬਸਿਡੀਆਂ",
                "scheme_col_name": "ਸਕੀਮ ਦਾ ਨਾਮ",
                "scheme_col_benefits": "ਲਾਭ",
                "scheme_col_docs": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
                "benefits": "ਲਾਭ",
                "required_docs": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
                "crop_advice_sec": "AI ਫਸਲ ਸਲਾਹ ਅਤੇ ਸਿਫ਼ਾਰਸ਼",
                "rec_crop": "ਸਿਫ਼ਾਰਸ਼ ਕੀਤੀ ਫਸਲ",
                "ai_insight": "ਖੇਤੀਬਾੜੀ ਮਾਹਿਰਾਂ ਦੀ ਸਲਾਹ",
                "summary_sec": "ਰਿਪੋਰਟ ਦਾ ਸੰਖੇਪ",
                "summary_text": "ਇਹ ਰਿਪੋਰਟ ਐਗਰੋਵਿਜ਼ਨ AI ਦੁਆਰਾ ਤਿਆਰ ਕੀਤੀ ਗਈ ਹੈ। ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਅਨੁਸਾਰ ਤੁਸੀਂ ਕਈ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਲਈ ਯੋਗ ਹੋ।",
                "match_label": "ਮੈਚ",
                "default_crop": "ਪ੍ਰੋਫਾਈਲ ਦੇ ਆਧਾਰ 'ਤੇ ਸਿਫਾਰਸ਼ ਕੀਤੀ ਗਈ",
                "default_reason": "ਤੁਹਾਡੀ ਜ਼ਮੀਨ ਅਨੁਸਾਰ ਢੁਕਵੀਆਂ ਸਕੀਮਾਂ ਮਿਲੀਆਂ ਹਨ।"
            },
            "ગુજરાતી": {
                "title": "એગ્રોવિઝન: AI ખેડૂત સત્તાવાર રિપોર્ટ",
                "gen_date": "રિપોર્ટની તારીખ",
                "profile_sec": "ખેડૂત પ્રોફાઇલ વિગતો",
                "name": "ખેડૂતનું નામ",
                "location": "રાજ્ય / જિલ્લો",
                "land_size": "જમીનનું ક્ષેત્રફળ",
                "land_type": "જમીનનો પ્રકાર",
                "irrigation": "સિંચાઈ સુવિધા",
                "crops": "મુખ્ય પાક",
                "schemes_sec": "પાત્ર સરકારી યોજનાઓ અને સબસિડી",
                "scheme_col_name": "યોજનાનું નામ",
                "scheme_col_benefits": "લાભો",
                "scheme_col_docs": "જરૂરી દસ્તાવેજો",
                "benefits": "લાભો",
                "required_docs": "જરૂરી દસ્તાવેજો",
                "crop_advice_sec": "AI પાક સલાહ અને ભલામણ",
                "rec_crop": "ભલામણ કરેલ પાક",
                "ai_insight": "કૃષિ નિષ્ણાત સલાહ",
                "summary_sec": "રિપોર્ટ સારાંશ",
                "summary_text": "આ રિપોર્ટ એગ્રોવિઝન AI દ્વારા તૈયાર કરવામાં આવ્યો છે. તમારી પ્રોફાઇલ મુજબ તમે અનેક સરકારી યોજનાઓ માટે પાત્ર છો.",
                "match_label": "મેચ",
                "default_crop": "પ્રોફાઇલ આધારિત પાક",
                "default_reason": "તમારી જમીન અને પાક મુજબ યોગ્ય યોજનાઓ મળી છે."
            }
        }

    def generate_report(self, farmer_data: dict, schemes: list, crop_recommendations: dict = None, language: str = "English") -> str:
        """
        Generates a beautifully formatted PDF report with ReportLab supporting Indic scripts.
        """
        lang = language if language in self.i18n else "English"
        t = self.i18n[lang]
        font_name = UNICODE_FONT or "Helvetica"

        farmer_name_clean = str(farmer_data.get('name', 'Farmer')).replace(' ', '_')
        filename = f"Report_{farmer_name_clean}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        filepath = os.path.join(self.reports_dir, filename)

        # Page Setup (A4: 595.27 x 841.89 pt. Printable width = 595 - 72 = 523pt)
        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=48
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'ReportTitle',
            fontName=font_name,
            fontSize=15,
            textColor=colors.HexColor('#ffffff'),
            alignment=1,
            leading=18
        )

        subtitle_style = ParagraphStyle(
            'ReportSubTitle',
            fontName=font_name,
            fontSize=9,
            textColor=colors.HexColor('#e2e8f0'),
            alignment=1,
            leading=12
        )

        sec_header_style = ParagraphStyle(
            'SecHeader',
            fontName=font_name,
            fontSize=11,
            textColor=colors.HexColor('#15803d'),
            spaceBefore=10,
            spaceAfter=6,
            leading=14
        )

        label_style = ParagraphStyle(
            'LabelStyle',
            fontName=font_name,
            fontSize=9.5,
            textColor=colors.HexColor('#1e293b'),
            leading=13
        )

        value_style = ParagraphStyle(
            'ValueStyle',
            fontName=font_name,
            fontSize=9.5,
            textColor=colors.HexColor('#334155'),
            leading=13
        )

        table_hdr_style = ParagraphStyle(
            'TblHdr',
            fontName=font_name,
            fontSize=9,
            textColor=colors.HexColor('#1e40af'),
            leading=12
        )

        body_style = ParagraphStyle(
            'BodyStyle',
            fontName=font_name,
            fontSize=9,
            textColor=colors.HexColor('#334155'),
            leading=13
        )

        docs_style = ParagraphStyle(
            'DocsStyle',
            fontName=font_name,
            fontSize=8.5,
            textColor=colors.HexColor('#475569'),
            leading=12
        )

        story = []

        # 1. Header Banner Box
        banner_data = [
            [Paragraph(f"<b>{xml_escape(t['title'])}</b>", title_style)],
            [Paragraph(f"{xml_escape(t['gen_date'])}: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Verified AgroVision AI Report", subtitle_style)]
        ]
        t_banner = Table(banner_data, colWidths=[523])
        t_banner.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#15803d')),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ]))
        story.append(t_banner)
        story.append(Spacer(1, 12))

        # 2. Farmer Profile Section
        story.append(Paragraph(f"<b>🚜 {xml_escape(t['profile_sec'])}</b>", sec_header_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0'), spaceAfter=8))

        # Values mapping for clean translation presentation
        land_type_val = farmer_data.get('land_type', 'Arable (Cultivable)')
        if lang in ["मराठी", "Marathi"] and "Arable" in str(land_type_val):
            land_type_val = "Arable (लागवडीयोग्य जमीन)"
        elif lang in ["हिंदी", "Hindi"] and "Arable" in str(land_type_val):
            land_type_val = "Arable (कृषि योग्य भूमि)"

        irrigation_val = farmer_data.get('irrigation_status', 'Rainfed')
        if lang in ["मराठी", "Marathi"] and "Rainfed" in str(irrigation_val):
            irrigation_val = "Rainfed (पावसावर आधारित)"
        elif lang in ["हिंदी", "Hindi"] and "Rainfed" in str(irrigation_val):
            irrigation_val = "Rainfed (वर्षा आधारित सिंचाई)"

        crops_val = farmer_data.get('crop_types') or farmer_data.get('crops') or "Paddy, Wheat"

        profile_rows = [
            [Paragraph(f"<b>{xml_escape(t['name'])}:</b>", label_style), Paragraph(xml_escape(farmer_data.get('name', 'N/A')), value_style)],
            [Paragraph(f"<b>{xml_escape(t['location'])}:</b>", label_style), Paragraph(xml_escape(farmer_data.get('state', 'Maharashtra')), value_style)],
            [Paragraph(f"<b>{xml_escape(t['land_size'])}:</b>", label_style), Paragraph(f"{farmer_data.get('land_size_acres', 'N/A')} Acres", value_style)],
            [Paragraph(f"<b>{xml_escape(t['land_type'])}:</b>", label_style), Paragraph(xml_escape(land_type_val), value_style)],
            [Paragraph(f"<b>{xml_escape(t['irrigation'])}:</b>", label_style), Paragraph(xml_escape(irrigation_val), value_style)],
            [Paragraph(f"<b>{xml_escape(t['crops'])}:</b>", label_style), Paragraph(xml_escape(crops_val), value_style)]
        ]

        t_prof = Table(profile_rows, colWidths=[140, 383])
        t_prof.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#f1f5f9')),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(t_prof)
        story.append(Spacer(1, 14))

        # 3. Eligible Schemes Section
        story.append(Paragraph(f"<b>🌾 {xml_escape(t['schemes_sec'])}</b>", ParagraphStyle('SchemeHdr', fontName=font_name, fontSize=11, textColor=colors.HexColor('#1d4ed8'), spaceBefore=6, spaceAfter=6)))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#93c5fd'), spaceAfter=8))

        if not schemes:
            story.append(Paragraph("No direct scheme matches found for current parameters.", body_style))
        else:
            schemes_tbl_data = [
                [
                    Paragraph(f"<b>{xml_escape(t['scheme_col_name'])}</b>", table_hdr_style),
                    Paragraph(f"<b>{xml_escape(t['scheme_col_benefits'])}</b>", table_hdr_style),
                    Paragraph(f"<b>{xml_escape(t['scheme_col_docs'])}</b>", table_hdr_style)
                ]
            ]

            for s in schemes[:5]:
                s_name = xml_escape(s.get('scheme_name', 'Government Scheme'))
                s_score = s.get('match_score', 95)
                s_benefits = xml_escape(s.get('benefits', 'Financial assistance and support'))
                s_docs = s.get('documents_required', ['Aadhaar Card', 'Land Records'])
                if isinstance(s_docs, list):
                    docs_text = xml_escape(", ".join(s_docs))
                else:
                    docs_text = xml_escape(str(s_docs))

                name_p = Paragraph(f"<b>{s_name}</b><br/><font color='#16a34a'><b>{s_score}% {xml_escape(t['match_label'])}</b></font>", body_style)
                ben_p = Paragraph(s_benefits, body_style)
                docs_p = Paragraph(docs_text, docs_style)
                schemes_tbl_data.append([name_p, ben_p, docs_p])

            # colWidths: 140pt + 233pt + 150pt = 523pt (Exact printable width)
            t_schemes = Table(schemes_tbl_data, colWidths=[140, 233, 150])
            t_schemes.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#eff6ff')),
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#bfdbfe')),
                ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 6),
                ('RIGHTPADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            story.append(t_schemes)

        story.append(Spacer(1, 14))

        # 4. AI Crop Advisor Recommendation Section
        if crop_recommendations:
            rec_crop_val = crop_recommendations.get('recommended_crop') or t['default_crop']
            if rec_crop_val == "Suggested based on profile":
                rec_crop_val = t['default_crop']

            reasoning_val = crop_recommendations.get('reasoning') or t['default_reason']
            if reasoning_val == "Matching schemes found for your specific land and crop types.":
                reasoning_val = t['default_reason']

            crop_rows = [
                [Paragraph(f"<b>🌱 {xml_escape(t['crop_advice_sec'])}</b>", ParagraphStyle('CropHdr', fontName=font_name, fontSize=11, textColor=colors.HexColor('#b45309'), spaceAfter=4))],
                [Paragraph(f"<b>{xml_escape(t['rec_crop'])}:</b> <font color='#15803d'><b>{xml_escape(rec_crop_val)}</b></font>", body_style)],
                [Paragraph(f"<b>{xml_escape(t['ai_insight'])}:</b> {xml_escape(reasoning_val)}", body_style)]
            ]

            t_crop = Table(crop_rows, colWidths=[523])
            t_crop.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fffbeb')),
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#fde68a')),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 10),
                ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ]))
            story.append(KeepTogether([t_crop]))
            story.append(Spacer(1, 14))

        # 5. Summary & Official Verification Section
        sum_data = [
            [Paragraph(f"<b>📋 {xml_escape(t['summary_sec'])}</b>", ParagraphStyle('SumHdr', fontName=font_name, fontSize=10, textColor=colors.HexColor('#0f172a')))],
            [Paragraph(xml_escape(t['summary_text']), body_style)]
        ]
        t_sum = Table(sum_data, colWidths=[523])
        t_sum.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f1f5f9')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ]))
        story.append(KeepTogether([t_sum]))

        # Build PDF using NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        return filepath


# Singleton instance
pdf_manager = ReportGenerator()
